Unit tests
rangle/angular2-ngrx-example pull request #10
Opened 2017-03-17 17:48 UTC by mdegani

2017-03-17 20:15 UTC, mdegani commented
work in progress, please don't merge

2017-03-28 11:05 UTC, mdegani commented on src/app/test/test-component-support.class.ts
> +  public querySelector(selector: string): any {
This was giving me a type error.

2017-03-28 11:06 UTC, mdegani commented on src/app/test/test-component-support.class.ts
>    }
Allow for case where there is no class.

2017-03-28 11:13 UTC, mdegani commented on src/app/test/test-component-support.class.spec.ts
> +  xit('should get the style', () => {
todo: look into the results of `.stlyle`.

2017-04-03 16:57 UTC, egervari requested changes

2017-04-03 16:57 UTC, egervari commented on src/app/root/services/api/api.service.spec.ts
> +      expect(spyHttpGet).toHaveBeenCalledWith('http://www.mocky.io/v2');
Why do spy's have their names prefix with `spy`? It's not really necessary.

2017-04-03 16:57 UTC, egervari commented on src/app/root/services/api/api.service.spec.ts
> +describe('the api service', () => {
Let's use `ApiService` in the describe so that the IDE can refactor it if the name should ever change

2017-04-03 16:57 UTC, egervari commented on src/app/loading/components/loading-container/loading-container.component.spec.ts
> +  let loadingContainer: LoadingContainerComponent;
I think a better way to test this component is to see if the various elements are visible or invisible depending on the various loading conditions.

2017-04-03 16:57 UTC, egervari commented on src/app/root/services/api/api.service.spec.ts
> +    apiService.get('').subscribe(() => {
Testing with `''` doesn't actually test the string concat functionality.

2017-04-03 16:57 UTC, egervari commented on src/app/test/test-component-support.class.spec.ts
> +                app-attr="abc"
we should probably put this in a `html` file, or at least format the template to be consistent with the rest of the html spacing/formatting. Also, let's not use `<div>` - it's an anti-pattern and I don't want to encourage it's use unless there is a very, very good reason. So we can use `<p>` or `<section>` or something like that instead.

2017-04-03 16:57 UTC, egervari commented on src/app/test/test-component-support.class.spec.ts
> +  template: `<div>
This doesn't even need any html contents actually.

2017-04-03 16:57 UTC, egervari commented on src/app/test/test-component-support.class.spec.ts
> +  beforeEach(() => {
Let's put in spacing between `beforeEach` and `it` to make the structure more readable.

2017-04-03 16:57 UTC, egervari commented on src/app/test/test-component-support.class.ts
> +    const component = <any>this.component;
come to think of it, we can probably use `this.component as any`

2017-04-03 16:57 UTC, egervari commented on src/app/video-games/components/video-games-container/video-games-container.component.spec.ts
> +    spyPlat = spyOn(mockPlatformsStore, 'retrieve');
Let's please not use short forms.

2017-04-03 18:24 UTC, egervari requested changes

2017-04-03 18:24 UTC, egervari commented on src/app/video-games/listing/components/video-game-filters/video-game-filters.component.spec.ts
> +describe('video game flters component', () => {
`flters` is a typo

2023-03-21 14:44 UTC, closed without merging